PACK = {
    "config_panel_title": "⚙️ <b>Vibe Config Panel</b>\nSelect a section below.",
    "config_panel_opened": "⚙️ Config panel was opened from inline.",
    "config_panel_missing_inline": "⚠️ <b>Config Panel</b>\nInline bot is not configured.\nRun <code>inline setup</code> first.",
    "config_category_core": "🧩 Core",
    "config_category_external": "🧪 External",
    "config_category_language": "🌐 Language",
    "config_no_modules_core": "📭 No core modules loaded.",
    "config_no_modules_external": "📭 No external modules loaded.",
    "config_back": "⬅️ Back",
    "config_language_title": "🌐 <b>Select Language</b>\nCurrent: <code>{language}</code>",
    "config_language_saved": "✅ Language updated: <code>{language}</code>",
    "config_module_not_found": "❌ Module not found.",
    "config_option_not_found": "❌ Option not found.",
    "config_option_alert": "⚙️ {label}: {value}\n{description}",
    "config_module_title": "📦 <b>{title}</b> <code>({name})</code>\n{description}",
    "setlanguage_opened": "🌐 Language menu was opened from inline.",
    "inline_start": "🤖 <b>Vibe Inline Bot</b>\n✅ Inline mode is ready.\n\nBot: <code>{inline_username}</code>\nPrefix: <code>{prefix}</code>\nUse the bot inline in any chat and call <code>config</code>, <code>language</code> or <code>info</code>.",
    "inline_default_title": "⚡ Vibe Inline",
    "inline_default_description": "Runtime status and available commands",
    "inline_default_text": "<b>⚡ Vibe Inline</b>\nPrefix: <code>{prefix}</code>\nCommands: <code>{commands}</code>",
    "language_article_title": "🌐 Language",
    "language_article_description": "Open language selection",
    "language_article_text": "🌐 <b>Language Selection</b>\nChoose a language below.",
}
