PACK = {
    "config_panel_title": "⚙️ <b>Панель конфигурации Vibe</b>\nВыбери раздел ниже.",
    "config_panel_opened": "⚙️ Меню конфигурации открыто через inline.",
    "config_panel_missing_inline": "⚠️ <b>Панель конфигурации</b>\nInline-бот не настроен.\nСначала выполни <code>inline setup</code>.",
    "config_category_core": "🧩 Core",
    "config_category_external": "🧪 External",
    "config_category_language": "🌐 Язык",
    "config_no_modules_core": "📭 Core-модули не загружены.",
    "config_no_modules_external": "📭 Внешние модули не загружены.",
    "config_back": "⬅️ Назад",
    "config_language_title": "🌐 <b>Выбор языка</b>\nТекущий: <code>{language}</code>",
    "config_language_saved": "✅ Язык изменён: <code>{language}</code>",
    "config_module_not_found": "❌ Модуль не найден.",
    "config_option_not_found": "❌ Опция не найдена.",
    "config_option_alert": "⚙️ {label}: {value}\n{description}",
    "config_module_title": "📦 <b>{title}</b> <code>({name})</code>\n{description}",
    "setlanguage_opened": "🌐 Меню выбора языка открыто через inline.",
    "inline_start": "🤖 <b>Inline-бот Vibe</b>\n✅ Inline-режим готов.\n\nБот: <code>{inline_username}</code>\nПрефикс: <code>{prefix}</code>\nИспользуй бота inline в любом чате и вызывай <code>config</code>, <code>language</code> или <code>info</code>.",
    "inline_default_title": "⚡ Vibe Inline",
    "inline_default_description": "Статус рантайма и доступные команды",
    "inline_default_text": "<b>⚡ Vibe Inline</b>\nПрефикс: <code>{prefix}</code>\nКоманды: <code>{commands}</code>",
    "language_article_title": "🌐 Язык",
    "language_article_description": "Открыть выбор языка",
    "language_article_text": "🌐 <b>Выбор языка</b>\nВыбери язык ниже.",
}
